version: '3'

services:
  # Веб-сервер на базе Nginx
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  # База данных Redis
  db:
    image: redis:alpine
    container_name: redis_db
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_MAXMEMORY=100mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    command: redis-server --appendonly yes

  # Инструмент для работы с Redis
  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: redis_commander
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:db:6379
    depends_on:
      - db

# Определение сети для связи контейнеров
networks:
  app-network:
    driver: bridge

# Определение томов для постоянного хранения данных
volumes:
  redis_data:
    driver: local 